python gen_mp_selfjoin.py 25
python gen_mp_selfjoin.py 50
python gen_mp_selfjoin.py 75
python gen_mp_selfjoin.py 100
python gen_mp_selfjoin.py 125
python gen_mp_selfjoin.py 150
python gen_mp_selfjoin.py 175
python gen_mp_selfjoin.py 200
python gen_mp_selfjoin.py 225
python gen_mp_selfjoin.py 250
python gen_mp_selfjoin.py 300
python gen_mp_selfjoin.py 350
python gen_mp_selfjoin.py 400
python gen_mp_selfjoin.py 450
python gen_mp_selfjoin.py 500
python gen_mp_selfjoin.py 550
python gen_mp_selfjoin.py 600
python gen_mp_selfjoin.py 650
python gen_mp_selfjoin.py 700
python gen_mp_selfjoin.py 750
python gen_mp_selfjoin.py 800
